### ISSUE TITLE
Transfer of plyranges to tidyomics organisation

### ISSUE THREAD

**Issue by sa-lee** [tidyomics/genomics-todos#15]
Hi all,

I have moved over the plyranges ownership to the tidyomics organisation, so this community can now contribute fully to the project. I wanted to say thanks for your continued interest in this work and to apologise for the lack of communication on issues. I no longer work fully in academia/bioinformatics so I would be grateful if someone on this team would like to take over maintanence and development of the package. I will still try and help out when I can 😄  

In the short term, in terms of maintanence I think these are most pressing:

- [ ] Update maintainer on bioc - any ideas from @mikelove would be appreciated
- [ ] Fix up any R CMD CHECK / WARNING issues
- [ ] Change default branch from master to main
- [ ] Update pkgdown website so it points to your org rather than my personal github pages
- [ ] Fix up CI/CD issues 

Cheers,
Stuart

**Comment by mikelove** [comment]
I think we’re done on all of these except I haven’t update codecov stats.

**Comment by sa-lee** [comment]
Great, closing this!

**Comment by mikelove** [comment]
Now passing check in devel:

![Screenshot 2024-04-13 at 11 49 04 AM](https://github.com/tidyomics/genomics-todos/assets/69203/2f69892a-665a-4e14-8524-6744ca41c91a)
